// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhamBenhAPI.Models;

#nullable disable

namespace QuanLyKhamBenhAPI.Migrations
{
    [DbContext(typeof(QuanLyKhamBenhContext))]
    [Migration("20251111111531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("appointmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("doctorId");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patientId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time")
                        .HasColumnName("time");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Appointm__D06765FEECC8698C");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.AppointmentService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("appointmentId");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("serviceId");

                    b.HasKey("Id")
                        .HasName("PK__Appointm__3213E83FB9DCB773");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ServiceId");

                    b.ToTable("AppointmentService", (string)null);
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("doctorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<int?>("SpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("specialtyId");

                    b.HasKey("DoctorId")
                        .HasName("PK__Doctor__7224847680FA0289");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Doctor", (string)null);
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feedbackId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("doctorId");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patientId");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__2613FD24E68EE594");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.LabResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("resultId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int?>("RecordId")
                        .HasColumnType("int")
                        .HasColumnName("recordId");

                    b.Property<DateTime?>("ResultDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("resultDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ResultDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("resultDetails");

                    b.HasKey("ResultId")
                        .HasName("PK__LabResul__C6EADC5B3EA11DC3");

                    b.HasIndex("RecordId");

                    b.ToTable("LabResult", (string)null);
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.LoyaltyPoint", b =>
                {
                    b.Property<int>("PointsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pointsId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PointsId"));

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("lastUpdated")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patientId");

                    b.Property<int?>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("points");

                    b.HasKey("PointsId")
                        .HasName("PK__LoyaltyP__1EA67FA8ED442AEE");

                    b.HasIndex("PatientId");

                    b.ToTable("LoyaltyPoints");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.MedicalRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("recordId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("appointmentId");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("diagnosis");

                    b.Property<string>("Symptoms")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("symptoms");

                    b.Property<string>("Treatment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("treatment");

                    b.HasKey("RecordId")
                        .HasName("PK__MedicalR__D825195E5D123E61");

                    b.HasIndex("AppointmentId");

                    b.ToTable("MedicalRecord", (string)null);
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("patientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.HasKey("PatientId")
                        .HasName("PK__Patient__A17005EC6575D4A7");

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paymentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("appointmentId");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("paymentDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("paymentMethod");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("totalAmount");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment__A0D9EFC6E22338D3");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.PaymentPromotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("paymentId");

                    b.Property<int?>("PromoId")
                        .HasColumnType("int")
                        .HasColumnName("promoId");

                    b.HasKey("Id")
                        .HasName("PK__PaymentP__3213E83FB9B7E1C8");

                    b.HasIndex("PaymentId");

                    b.HasIndex("PromoId");

                    b.ToTable("PaymentPromotion", (string)null);
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Promotion", b =>
                {
                    b.Property<int>("PromoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("promoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromoId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("discountPercent");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("endDate");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("startDate");

                    b.HasKey("PromoId")
                        .HasName("PK__Promotio__E19E71F6D52E2CA9");

                    b.ToTable("Promotion", (string)null);
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("serviceId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.HasKey("ServiceId")
                        .HasName("PK__Service__455070DF9211E9E6");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Specialty", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("specialtyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialtyId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("SpecialtyId")
                        .HasName("PK__Specialt__81FB91AEE20C0732");

                    b.ToTable("Specialty", (string)null);
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.UserAccount", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("doctorId");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("passwordHash");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patientId");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PK__UserAcco__CB9A1CFFF0632199");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex(new[] { "Username" }, "UQ__UserAcco__F3DBC57263F32EF0")
                        .IsUnique();

                    b.ToTable("UserAccount", (string)null);
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.WorkShift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shiftId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("doctorId");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("endTime");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("startTime");

                    b.HasKey("ShiftId")
                        .HasName("PK__WorkShif__F2F06B02BBC70987");

                    b.HasIndex("DoctorId");

                    b.ToTable("WorkShift", (string)null);
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Appointment", b =>
                {
                    b.HasOne("QuanLyKhamBenhAPI.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("FK__Appointme__docto__46E78A0C");

                    b.HasOne("QuanLyKhamBenhAPI.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK__Appointme__patie__45F365D3");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.AppointmentService", b =>
                {
                    b.HasOne("QuanLyKhamBenhAPI.Models.Appointment", "Appointment")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("FK__Appointme__appoi__4BAC3F29");

                    b.HasOne("QuanLyKhamBenhAPI.Models.Service", "Service")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK__Appointme__servi__4CA06362");

                    b.Navigation("Appointment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Doctor", b =>
                {
                    b.HasOne("QuanLyKhamBenhAPI.Models.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .HasConstraintName("FK__Doctor__specialt__398D8EEE");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Feedback", b =>
                {
                    b.HasOne("QuanLyKhamBenhAPI.Models.Doctor", "Doctor")
                        .WithMany("Feedbacks")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("FK__Feedback__doctor__68487DD7");

                    b.HasOne("QuanLyKhamBenhAPI.Models.Patient", "Patient")
                        .WithMany("Feedbacks")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK__Feedback__patien__6754599E");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.LabResult", b =>
                {
                    b.HasOne("QuanLyKhamBenhAPI.Models.MedicalRecord", "Record")
                        .WithMany("LabResults")
                        .HasForeignKey("RecordId")
                        .HasConstraintName("FK__LabResult__recor__5441852A");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.LoyaltyPoint", b =>
                {
                    b.HasOne("QuanLyKhamBenhAPI.Models.Patient", "Patient")
                        .WithMany("LoyaltyPoints")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK__LoyaltyPo__patie__628FA481");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.MedicalRecord", b =>
                {
                    b.HasOne("QuanLyKhamBenhAPI.Models.Appointment", "Appointment")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("FK__MedicalRe__appoi__5070F446");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Payment", b =>
                {
                    b.HasOne("QuanLyKhamBenhAPI.Models.Appointment", "Appointment")
                        .WithMany("Payments")
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("FK__Payment__appoint__5812160E");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.PaymentPromotion", b =>
                {
                    b.HasOne("QuanLyKhamBenhAPI.Models.Payment", "Payment")
                        .WithMany("PaymentPromotions")
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("FK__PaymentPr__payme__5CD6CB2B");

                    b.HasOne("QuanLyKhamBenhAPI.Models.Promotion", "Promo")
                        .WithMany("PaymentPromotions")
                        .HasForeignKey("PromoId")
                        .HasConstraintName("FK__PaymentPr__promo__5DCAEF64");

                    b.Navigation("Payment");

                    b.Navigation("Promo");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.UserAccount", b =>
                {
                    b.HasOne("QuanLyKhamBenhAPI.Models.Doctor", "Doctor")
                        .WithMany("UserAccounts")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("FK__UserAccou__docto__3F466844");

                    b.HasOne("QuanLyKhamBenhAPI.Models.Patient", "Patient")
                        .WithMany("UserAccounts")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK__UserAccou__patie__403A8C7D");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.WorkShift", b =>
                {
                    b.HasOne("QuanLyKhamBenhAPI.Models.Doctor", "Doctor")
                        .WithMany("WorkShifts")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("FK__WorkShift__docto__4316F928");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentServices");

                    b.Navigation("MedicalRecords");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Feedbacks");

                    b.Navigation("UserAccounts");

                    b.Navigation("WorkShifts");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.MedicalRecord", b =>
                {
                    b.Navigation("LabResults");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Feedbacks");

                    b.Navigation("LoyaltyPoints");

                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Payment", b =>
                {
                    b.Navigation("PaymentPromotions");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Promotion", b =>
                {
                    b.Navigation("PaymentPromotions");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Service", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("QuanLyKhamBenhAPI.Models.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
